### ISSUE TITLE
Missing data for River Frome

### ISSUE THREAD

**Issue by seagulljim** [top-poop/top-of-the-poops#14]
The data you have for Rode (on the River Frome, in the Somerton & Frome constituency) is missing the figures for the Rode Wastewater Treatment Works (permit 11560 - 82 overflows, for 1248 hours). You are only showing the data for the much smaller overflow - permit 100190)

**Comment by top-poop** [comment]
Thanks for reporting this - we'll take a look.

**Comment by top-poop** [comment]
Hi - The Environment Agency Data is a bit of a mess. This particular issue is caused by a duplicate consent/permit number, 011560, which has been allocated to two different CSOs, one in Somerset, and one in Fylde. We'll see if we can do something to make it allocate it to the right place. Although superficially it may seem easy to do, there are loads of inconsistencies in the data which means making it work across al the thousands of different CSOs is a bit tricky.

**Comment by top-poop** [comment]
Thanks for pointing this out - you should be able to see updated figures on the site now.

**Comment by seagulljim** [comment]
Great - that was quick!
